# Site settings
title: George Hunter
email: georgehunter025@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  George Hunter's Website
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://georgehunter.github.io" # the base hostname & protocol for your site
url: "http://localhost:4000"
twitter_username: 
github_username:  georgehunter
permalinks: pretty

# Build settings
markdown: kramdown
